# development
system:
  # url前缀
  url-path-prefix: api
  # gin模式 debug|release
  app-mode: debug
  # 开启全局事务管理器
  transaction: true
  # 操作日志key
  operation-log-key: operlog_response
  # 程序监听端口
  port: 8000

mysql:
  # 用户名
  username: anew
  # 密码
  password: anew@123
  # 数据库名
  database: anew_db
  # 主机地址
  host: 192.168.56.100
  # 端口
  port: 3306
  # 连接字符串查询参数
  query: charset=utf8&parseTime=True&loc=Local&timeout=10000ms
  # 是否打印SQL日志
  log-mode: true
  # 数据库表前缀
  table-prefix: tb_
  # 编码方式
  charset: utf8mb4
  # 字符集(utf8mb4_general_ci速度比utf8mb4_unicode_ci快些)
  collation: utf8mb4_general_ci

logs:
  # 日志等级(-1:Debug, 0:Info, -1<=level<=5, 参照zap.level源码)
  level: -1
  # 日志路径
  path: logs
  # 文件最大大小, M
  max-size: 50
  # 备份数
  max-backups: 100
  # 存放时间, 天
  max-age: 30
  # 是否压缩
  compress: false

# jwt配置
jwt:
  # jwt标识
  realm: anew
  # 服务端密钥
  key: vFr3RRkxlBG0ggRYLG
  # token过期时间, 小时
  timeout: 24
  # token更新时间, 小时
  max-refresh: 24

# casbin配置
casbin:
  # 模型配置文件, 默认以conf目录为根目录
  model-path: 'rbac_model.conf'

# 上传配置
upload:
  # 上传文件保存路径
  save-dir: upload
  # 单个文件或分片文件最大限制, 单位MB(上传文件先读取到内存, 如果这个值设置过大会导致内存崩溃)
  single-max-size: 32
  # 合并文件并发数(并发合并文件会提升性能, 但如果设置过大性能降低, 结合实际机器性能配置)
  merge-concurrent-count: 10
