# development
system:
  # gin模式 debug|release
  app-mode: debug
  # 程序监听端口
  port: 8000

mysql:
  # 用户名
  username: anew
  # 密码
  password: anew@123
  # 数据库名
  database: anew_db
  # 主机地址
  host: 192.168.56.100
  # 端口
  port: 3306
  # 连接字符串查询参数
  query: charset=utf8&parseTime=True&loc=Local&timeout=10000ms
  # 是否打印日志
  log-mode: true
  # 数据库表前缀
  table-prefix: tb_
  # 编码方式
  charset: utf8mb4
  # 字符集(utf8mb4_general_ci速度比utf8mb4_unicode_ci快些)
  collation: utf8mb4_general_ci

  logs:
    # 日志等级(-1:Debug, 0:Info, -1<=level<=5, 参照zap.level源码)
    level: -1
    # 日志路径
    path: logs
    # 文件最大大小, M
    max-size: 50
    # 备份数
    max-backups: 100
    # 存放时间, 天
    max-age: 30
    # 是否压缩
    compress: false